version: '{build}'

image: Visual Studio 2017
configuration: Release

before_build:
- dotnet restore

build:
  verbosity: minimal

artifacts:
- path: Hashsum\bin\$(configuration)\Hashsum*.nupkg
  name: Hashsum.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 5VyEaGo5gRLr9HdkRFqS1enRq+K8Qarg1dzU33CE1dOmVXp43JaS2PQTNgsRHXkc
  artifact: Hashsum.nupkg
  on:
    branch: master
    appveyor_repo_tag: true